/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantRunnersRouteImport } from './routes/restaurant.runners'
import { Route as RestaurantMenuRouteImport } from './routes/restaurant.menu'
import { Route as RestaurantKitchenRouteImport } from './routes/restaurant.kitchen'
import { Route as RestaurantInventoryRouteImport } from './routes/restaurant.inventory'
import { Route as RestaurantDashboardRouteImport } from './routes/restaurant.dashboard'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRunnersRoute = RestaurantRunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantMenuRoute = RestaurantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantKitchenRoute = RestaurantKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantInventoryRoute = RestaurantInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantDashboardRoute = RestaurantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RestaurantRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/register': typeof RegisterRoute
  '/restaurant': typeof RestaurantRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/inventory': typeof RestaurantInventoryRoute
  '/restaurant/kitchen': typeof RestaurantKitchenRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/runners': typeof RestaurantRunnersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/register': typeof RegisterRoute
  '/restaurant': typeof RestaurantRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/inventory': typeof RestaurantInventoryRoute
  '/restaurant/kitchen': typeof RestaurantKitchenRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/runners': typeof RestaurantRunnersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/register': typeof RegisterRoute
  '/restaurant': typeof RestaurantRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/inventory': typeof RestaurantInventoryRoute
  '/restaurant/kitchen': typeof RestaurantKitchenRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/runners': typeof RestaurantRunnersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/employee'
    | '/login'
    | '/menu'
    | '/register'
    | '/restaurant'
    | '/orders/$id'
    | '/restaurant/dashboard'
    | '/restaurant/inventory'
    | '/restaurant/kitchen'
    | '/restaurant/menu'
    | '/restaurant/runners'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/employee'
    | '/login'
    | '/menu'
    | '/register'
    | '/restaurant'
    | '/orders/$id'
    | '/restaurant/dashboard'
    | '/restaurant/inventory'
    | '/restaurant/kitchen'
    | '/restaurant/menu'
    | '/restaurant/runners'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/employee'
    | '/login'
    | '/menu'
    | '/register'
    | '/restaurant'
    | '/orders/$id'
    | '/restaurant/dashboard'
    | '/restaurant/inventory'
    | '/restaurant/kitchen'
    | '/restaurant/menu'
    | '/restaurant/runners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  EmployeeRoute: typeof EmployeeRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  RegisterRoute: typeof RegisterRoute
  RestaurantRoute: typeof RestaurantRouteWithChildren
  OrdersIdRoute: typeof OrdersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/runners': {
      id: '/restaurant/runners'
      path: '/runners'
      fullPath: '/restaurant/runners'
      preLoaderRoute: typeof RestaurantRunnersRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/menu': {
      id: '/restaurant/menu'
      path: '/menu'
      fullPath: '/restaurant/menu'
      preLoaderRoute: typeof RestaurantMenuRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/kitchen': {
      id: '/restaurant/kitchen'
      path: '/kitchen'
      fullPath: '/restaurant/kitchen'
      preLoaderRoute: typeof RestaurantKitchenRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/inventory': {
      id: '/restaurant/inventory'
      path: '/inventory'
      fullPath: '/restaurant/inventory'
      preLoaderRoute: typeof RestaurantInventoryRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/dashboard': {
      id: '/restaurant/dashboard'
      path: '/dashboard'
      fullPath: '/restaurant/dashboard'
      preLoaderRoute: typeof RestaurantDashboardRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RestaurantRouteChildren {
  RestaurantDashboardRoute: typeof RestaurantDashboardRoute
  RestaurantInventoryRoute: typeof RestaurantInventoryRoute
  RestaurantKitchenRoute: typeof RestaurantKitchenRoute
  RestaurantMenuRoute: typeof RestaurantMenuRoute
  RestaurantRunnersRoute: typeof RestaurantRunnersRoute
}

const RestaurantRouteChildren: RestaurantRouteChildren = {
  RestaurantDashboardRoute: RestaurantDashboardRoute,
  RestaurantInventoryRoute: RestaurantInventoryRoute,
  RestaurantKitchenRoute: RestaurantKitchenRoute,
  RestaurantMenuRoute: RestaurantMenuRoute,
  RestaurantRunnersRoute: RestaurantRunnersRoute,
}

const RestaurantRouteWithChildren = RestaurantRoute._addFileChildren(
  RestaurantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  EmployeeRoute: EmployeeRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  RegisterRoute: RegisterRoute,
  RestaurantRoute: RestaurantRouteWithChildren,
  OrdersIdRoute: OrdersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
